FROM debian:12

RUN apt update && apt install -y python3 git tar build-essential
RUN apt install -y cmake python3 build-essential gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

WORKDIR /mnt
